export enum SubCategory {
  FOOD = 'FOOD',
  WATER = 'WATER',
  DIAPERS = 'DIAPERS',
  MILK = 'MILK',
  MEDICINE = 'MEDICINE',
  BEDDING = 'BEDDING',
  CLOTHES = 'CLOTHES',
  SURGERY = 'SURGERY',
  HOSPITAL = 'HOSPITAL',
  RENT = 'RENT',
  FURNITURE_TRANSPORT = 'FURNITURE_TRANSPORT',
}
