import {
  HelpRequestStatus,
  HelpType,
  PriorityLevel,
  SubCategory,
  Visibility,
  type HelpRequest,
} from "./types"

export const MOCK_HELP_REQUESTS: HelpRequest[] = [
  {
    _id: "hr_001",
    createdBy: "mock_user_1",
    title: "Baby formula and diapers",
    description:
      "Family displaced from the south needs infant formula (stage 1) and diapers size 3 for two children under 2 years old.",
    helpType: HelpType.MATERIAL,
    subCategory: SubCategory.DIAPERS,
    priorityLevel: PriorityLevel.HIGH,
    quantity: { required: 20, fulfilled: 8, remaining: 12, unit: "packs" },
    beneficiariesCount: 4,
    location: {
      governorate: "Mount Lebanon",
      district: "Baabda",
      city: "Hazmieh",
    },
    status: HelpRequestStatus.PARTIALLY_FULFILLED,
    visibility: Visibility.PUBLIC,
    isVerified: true,
    contactPhone: "+96170123456",
    createdAt: "2026-05-20T10:00:00.000Z",
    updatedAt: "2026-05-22T14:30:00.000Z",
  },
  {
    _id: "hr_002",
    createdBy: "user_2",
    title: "Rent assistance — 3 months",
    description:
      "Elderly couple unable to cover rent after building damage. Seeking financial support for three months while repairs are assessed.",
    helpType: HelpType.FINANCIAL,
    subCategory: SubCategory.RENT,
    priorityLevel: PriorityLevel.CRITICAL,
    quantity: { required: 1, fulfilled: 0, remaining: 1, unit: "case" },
    beneficiariesCount: 2,
    location: {
      governorate: "Beirut",
      district: "Beirut",
      city: "Achrafieh",
    },
    status: HelpRequestStatus.ACTIVE,
    visibility: Visibility.PUBLIC,
    isVerified: false,
    createdAt: "2026-05-21T08:15:00.000Z",
    updatedAt: "2026-05-21T08:15:00.000Z",
  },
  {
    _id: "hr_003",
    createdBy: "user_3",
    title: "Transport to hospital for surgery",
    description:
      "Patient scheduled for surgery next week needs reliable transport from Tripoli to Beirut hospital and return trip.",
    helpType: HelpType.MEDICAL,
    subCategory: SubCategory.SURGERY,
    priorityLevel: PriorityLevel.HIGH,
    quantity: { required: 2, fulfilled: 2, remaining: 0, unit: "trips" },
    beneficiariesCount: 1,
    location: {
      governorate: "North",
      district: "Tripoli",
      city: "Tripoli",
    },
    status: HelpRequestStatus.FULFILLED,
    visibility: Visibility.PUBLIC,
    isVerified: true,
    createdAt: "2026-05-18T16:45:00.000Z",
    updatedAt: "2026-05-19T11:00:00.000Z",
  },
  {
    _id: "hr_004",
    createdBy: "user_4",
    title: "Clean drinking water — weekly delivery",
    description:
      "Shelter hosting 30 families requires weekly water delivery until municipal supply is restored.",
    helpType: HelpType.MATERIAL,
    subCategory: SubCategory.WATER,
    priorityLevel: PriorityLevel.MEDIUM,
    quantity: { required: 12, fulfilled: 4, remaining: 8, unit: "deliveries" },
    beneficiariesCount: 30,
    location: {
      governorate: "Bekaa",
      district: "Zahle",
      city: "Chtaura",
    },
    status: HelpRequestStatus.PARTIALLY_FULFILLED,
    visibility: Visibility.PUBLIC,
    isVerified: true,
    createdAt: "2026-05-19T09:00:00.000Z",
    updatedAt: "2026-05-23T07:20:00.000Z",
  },
  {
    _id: "hr_005",
    createdBy: "user_5",
    title: "Winter clothing for children",
    description:
      "Distribution completed for 15 families. Request closed after final delivery.",
    helpType: HelpType.MATERIAL,
    subCategory: SubCategory.CLOTHES,
    priorityLevel: PriorityLevel.LOW,
    quantity: { required: 30, fulfilled: 30, remaining: 0, unit: "sets" },
    beneficiariesCount: 15,
    location: {
      governorate: "South",
      district: "Saida",
      city: "Saida",
    },
    status: HelpRequestStatus.FULFILLED,
    visibility: Visibility.PUBLIC,
    isVerified: true,
    createdAt: "2026-04-10T12:00:00.000Z",
    updatedAt: "2026-05-01T18:00:00.000Z",
  },
  {
    _id: "hr_006",
    createdBy: "user_6",
    title: "Medicine refill — expired listing",
    description:
      "Request expired before fulfillment. Family sourced medication through another channel.",
    helpType: HelpType.MEDICAL,
    subCategory: SubCategory.MEDICINE,
    priorityLevel: PriorityLevel.MEDIUM,
    quantity: { required: 5, fulfilled: 0, remaining: 5, unit: "boxes" },
    location: {
      governorate: "Beirut",
      district: "Beirut",
      city: "Hamra",
    },
    status: HelpRequestStatus.EXPIRED,
    visibility: Visibility.PUBLIC,
    isVerified: false,
    createdAt: "2026-03-01T09:00:00.000Z",
    updatedAt: "2026-04-01T09:00:00.000Z",
  },
]
